version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: 
      context: .
      args:
        - http_proxy=$HTTP_PROXY

  redis:
    extends:
      file: common.yml
      service: redis
